Fix fixme: replace assert with Result::Err
Instead of a user getting:

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `13341906656571756929`,
 right: `13341906656571756928`', src/slab.rs:301:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

They will now get this:

couldn't open hashes slab file

Caused by:
    slab file magic is invalid or corrupt, actual 13341906656571756929 != 13341906656571756928 expected

Which should be slightly more helpful.

This was done for slab header which includes magic, version, and flags.
Common code was also moved to a shared to validate.

Signed-off-by: Tony Asleson <tasleson@redhat.com>